// =============================================================================
// DOTDESIGNPOP POWER BI - DAX MEASURES
// Generated for Power BI Import
// =============================================================================

// -----------------------------------------------------------------------------
// FOLDER: Revenue & Financial
// -----------------------------------------------------------------------------

Total Revenue =
SUM(Sales_Transactions[Net_Price])

Total Cost =
SUM(Sales_Transactions[Unit_Cost])

Gross Profit =
[Total Revenue] - [Total Cost]

Profit Margin % =
DIVIDE([Gross Profit], [Total Revenue], 0) * 100

Avg Transaction Value =
AVERAGE(Sales_Transactions[Net_Price])

Total Discounts =
SUM(Sales_Transactions[Discount])

// -----------------------------------------------------------------------------
// FOLDER: Inventory
// -----------------------------------------------------------------------------

Units in Stock =
CALCULATE(
    COUNTROWS(Inventory),
    Inventory[Status] = "In Stock"
)

Units Shipped =
CALCULATE(
    COUNTROWS(Inventory),
    Inventory[Status] IN {"Shipped", "Delivered", "In Transit"}
)

Inventory Value =
SUMX(
    Inventory,
    RELATED(SKU_Master[Unit_Cost])
)

Stock Count =
COUNTROWS(Inventory)

Avg Days in Stock =
AVERAGEX(
    FILTER(Inventory, Inventory[Status] = "In Stock"),
    DATEDIFF(Inventory[Received_Date], TODAY(), DAY)
)

// -----------------------------------------------------------------------------
// FOLDER: Shipments
// -----------------------------------------------------------------------------

Total Shipments =
COUNTROWS(Shipments)

Delivered Shipments =
CALCULATE(
    COUNTROWS(Shipments),
    Shipments[Delivery_Status] = "Delivered"
)

On-Time Delivery % =
VAR DeliveredOnTime =
    CALCULATE(
        COUNTROWS(Shipments),
        Shipments[Delivery_Status] = "Delivered",
        DATEDIFF(Shipments[Ship_Date], Shipments[Delivery_Date], DAY) <= 7
    )
VAR TotalDelivered = [Delivered Shipments]
RETURN
    DIVIDE(DeliveredOnTime, TotalDelivered, 0) * 100

Avg Delivery Days =
AVERAGEX(
    FILTER(Shipments, Shipments[Delivery_Status] = "Delivered"),
    DATEDIFF(Shipments[Ship_Date], Shipments[Delivery_Date], DAY)
)

Total Shipping Cost =
SUM(Shipments[Shipping_Cost])

Avg Shipping Cost =
AVERAGE(Shipments[Shipping_Cost])

// -----------------------------------------------------------------------------
// FOLDER: Service
// -----------------------------------------------------------------------------

Total Service Requests =
COUNTROWS(Service_Records)

Completed Services =
CALCULATE(
    COUNTROWS(Service_Records),
    Service_Records[Service_Status] = "Completed"
)

Service Completion % =
DIVIDE([Completed Services], [Total Service Requests], 0) * 100

Avg Service Cost =
AVERAGE(Service_Records[Total_Cost])

Warranty Claims =
CALCULATE(
    COUNTROWS(Service_Records),
    Service_Records[Warranty_Status] = "Under Warranty"
)

Warranty Claim % =
DIVIDE([Warranty Claims], [Total Service Requests], 0) * 100

Avg Service Days =
AVERAGEX(
    FILTER(Service_Records, Service_Records[Service_Status] = "Completed"),
    DATEDIFF(Service_Records[Service_Request_Date], Service_Records[Completed_Date], DAY)
)

Total Labor Hours =
SUM(Service_Records[Labor_Hours])

Service Revenue =
SUM(Service_Records[Total_Cost])

// -----------------------------------------------------------------------------
// FOLDER: Time Intelligence
// -----------------------------------------------------------------------------

Revenue YTD =
TOTALYTD([Total Revenue], Date_Dimension[Date])

Revenue SPLY =
CALCULATE(
    [Total Revenue],
    SAMEPERIODLASTYEAR(Date_Dimension[Date])
)

Revenue YoY Growth =
VAR CurrentYear = [Total Revenue]
VAR LastYear = [Revenue SPLY]
RETURN
    DIVIDE(CurrentYear - LastYear, LastYear, 0) * 100

Revenue YoY Change =
[Total Revenue] - [Revenue SPLY]

Revenue QTD =
TOTALQTD([Total Revenue], Date_Dimension[Date])

Revenue MTD =
TOTALMTD([Total Revenue], Date_Dimension[Date])

Revenue Previous Month =
CALCULATE(
    [Total Revenue],
    PREVIOUSMONTH(Date_Dimension[Date])
)

Revenue MoM % =
VAR CurrentMonth = [Total Revenue]
VAR PreviousMonth = [Revenue Previous Month]
RETURN
    DIVIDE(CurrentMonth - PreviousMonth, PreviousMonth, 0) * 100

Revenue 3M Avg =
AVERAGEX(
    DATESINPERIOD(
        Date_Dimension[Date],
        LASTDATE(Date_Dimension[Date]),
        -3,
        MONTH
    ),
    [Total Revenue]
)

Shipments 7D Avg =
AVERAGEX(
    DATESINPERIOD(
        Date_Dimension[Date],
        LASTDATE(Date_Dimension[Date]),
        -7,
        DAY
    ),
    [Total Shipments]
)

// -----------------------------------------------------------------------------
// FOLDER: Customer Analytics
// -----------------------------------------------------------------------------

Customer LTV =
SUMX(
    VALUES(Clients[Client_ID]),
    CALCULATE([Total Revenue])
)

Avg Revenue per Customer =
DIVIDE([Total Revenue], DISTINCTCOUNT(Sales_Transactions[Client_ID]), 0)

VIP Revenue =
CALCULATE(
    [Total Revenue],
    Clients[VIP_Status] IN {"Gold", "Platinum"}
)

VIP Revenue % =
DIVIDE([VIP Revenue], [Total Revenue], 0) * 100

Top Customer Revenue =
VAR TopCustomerCount = CEILING(DISTINCTCOUNT(Clients[Client_ID]) * 0.1, 1)
VAR TopCustomers =
    TOPN(
        TopCustomerCount,
        VALUES(Clients[Client_ID]),
        [Total Revenue],
        DESC
    )
RETURN
    CALCULATE([Total Revenue], TopCustomers)

// -----------------------------------------------------------------------------
// FOLDER: Product Performance
// -----------------------------------------------------------------------------

Best SKU =
FIRSTNONBLANK(
    TOPN(1, VALUES(SKU_Master[Product_Name]), [Units Shipped], DESC),
    1
)

SKU Revenue % =
DIVIDE(
    [Total Revenue],
    CALCULATE([Total Revenue], ALL(SKU_Master)),
    0
) * 100

Product Mix Index =
SUMX(
    VALUES(SKU_Master[SKU_Code]),
    POWER([SKU Revenue %] / 100, 2)
)

// -----------------------------------------------------------------------------
// FOLDER: Variance Analysis
// -----------------------------------------------------------------------------

Revenue Variance =
VAR ActualRevenue = [Total Revenue]
VAR BudgetRevenue = SUM(Budget_Targets[Target_Revenue])
RETURN
    ActualRevenue - BudgetRevenue

Revenue Variance % =
DIVIDE([Revenue Variance], SUM(Budget_Targets[Target_Revenue]), 0) * 100

Shipments Variance =
[Total Shipments] - SUM(Budget_Targets[Target_Shipments])

Service Performance =
[Service Completion %] - AVERAGE(Budget_Targets[Target_Service_Completion_Rate])

// -----------------------------------------------------------------------------
// FOLDER: Regional Performance
// -----------------------------------------------------------------------------

Regional Market Share % =
DIVIDE(
    [Total Revenue],
    CALCULATE([Total Revenue], ALL(Geography[Region])),
    0
) * 100

Region Rank =
RANKX(
    ALL(Geography[Region]),
    [Total Revenue],
    ,
    DESC,
    Dense
)

Top Region =
FIRSTNONBLANK(
    TOPN(1, VALUES(Geography[Region]), [Total Revenue], DESC),
    1
)

// -----------------------------------------------------------------------------
// FOLDER: KPI Status
// -----------------------------------------------------------------------------

KPI Status =
SWITCH(
    TRUE(),
    [Revenue YoY Growth] >= 20, "Excellent",
    [Revenue YoY Growth] >= 10, "Good",
    [Revenue YoY Growth] >= 0, "Fair",
    "Poor"
)

Service SLA Status =
IF([Service Completion %] >= 90, "Met", "Not Met")

Delivery Status =
SWITCH(
    TRUE(),
    [On-Time Delivery %] >= 95, "Excellent",
    [On-Time Delivery %] >= 85, "Good",
    [On-Time Delivery %] >= 75, "Fair",
    "Poor"
)

Revenue Achievement % =
DIVIDE([Total Revenue], SUM(Budget_Targets[Target_Revenue]), 0) * 100

Target Status =
IF([Revenue Achievement %] >= 100, "Target Met", "Below Target")

// -----------------------------------------------------------------------------
// FOLDER: Customer Satisfaction
// -----------------------------------------------------------------------------

Customer Satisfaction =
AVERAGE(Shipments[Delivery_Rating])

Avg Customer Satisfaction =
AVERAGE(Service_Records[Customer_Satisfaction])

// =============================================================================
// FOLDER: Warehouse / Storage (NEW TAB)
// =============================================================================

// Units expected but not yet received in warehouse
Pending Arrival =
CALCULATE(
    COUNTROWS(Inventory),
    Inventory[Status] IN {"Pending", "Ordered", "In Transit to Warehouse"}
)

// Units physically in warehouse and available for allocation
Available Inventory =
CALCULATE(
    COUNTROWS(Inventory),
    Inventory[Status] IN {"In Stock", "Available", "Ready"}
)

// Units that have left the warehouse (shipped out)
Exited Warehouse =
CALCULATE(
    COUNTROWS(Inventory),
    Inventory[Status] IN {"Shipped", "Delivered", "In Transit", "Deployed"}
)

// Total warehouse throughput
Warehouse Throughput =
[Pending Arrival] + [Available Inventory] + [Exited Warehouse]

// Warehouse utilization rate
Warehouse Fill Rate % =
DIVIDE([Available Inventory], [Warehouse Throughput], 0) * 100

// Units pending by SKU (for drill-down)
Pending by SKU =
CALCULATE(
    COUNTROWS(Inventory),
    Inventory[Status] IN {"Pending", "Ordered", "In Transit to Warehouse"}
)

// =============================================================================
// FOLDER: Active Shipments (NEW TAB)
// =============================================================================

// Shipments currently in transit
Shipments In Transit =
CALCULATE(
    COUNTROWS(Shipments),
    Shipments[Delivery_Status] = "In Transit"
)

// Shipments pending pickup/processing
Shipments Pending =
CALCULATE(
    COUNTROWS(Shipments),
    Shipments[Delivery_Status] IN {"Pending", "Processing", "Awaiting Pickup"}
)

// Shipments out for delivery
Shipments Out for Delivery =
CALCULATE(
    COUNTROWS(Shipments),
    Shipments[Delivery_Status] = "Out for Delivery"
)

// Shipments delivered (completed)
Shipments Completed =
CALCULATE(
    COUNTROWS(Shipments),
    Shipments[Delivery_Status] = "Delivered"
)

// Active shipments (not yet delivered)
Active Shipments =
[Shipments In Transit] + [Shipments Pending] + [Shipments Out for Delivery]

// Shipment status breakdown
Shipment Status Summary =
CONCATENATEX(
    SUMMARIZE(
        Shipments,
        Shipments[Delivery_Status],
        "Count", COUNTROWS(Shipments)
    ),
    Shipments[Delivery_Status] & ": " & [Count],
    ", "
)

// =============================================================================
// FOLDER: Warranty & Service (NEW TAB)
// =============================================================================

// Active warranties by Serial Number count
Active Warranties =
CALCULATE(
    DISTINCTCOUNT(Service_Records[Serial_Number]),
    Service_Records[Warranty_Status] = "Under Warranty"
)

// Units with active warranty (from Inventory perspective)
Units Under Warranty =
VAR WarrantyDays = 365  // Default warranty period
RETURN
CALCULATE(
    COUNTROWS(Inventory),
    FILTER(
        Inventory,
        DATEDIFF(Inventory[Received_Date], TODAY(), DAY) <=
            RELATED(SKU_Master[Warranty_Period_Days])
    )
)

// Service requests submitted (not yet scheduled)
Service Requested =
CALCULATE(
    COUNTROWS(Service_Records),
    Service_Records[Service_Status] IN {"Requested", "Open", "Submitted", "Pending Review"}
)

// Repairs that have been scheduled
Repair Scheduled =
CALCULATE(
    COUNTROWS(Service_Records),
    Service_Records[Service_Status] IN {"Scheduled", "In Progress", "Assigned"},
    NOT(ISBLANK(Service_Records[Scheduled_Date]))
)

// Expired warranties
Expired Warranties =
CALCULATE(
    DISTINCTCOUNT(Service_Records[Serial_Number]),
    Service_Records[Warranty_Status] = "Expired"
)

// Warranty expiring soon (next 30 days)
Warranty Expiring Soon =
VAR WarrantyDays = 365
RETURN
CALCULATE(
    COUNTROWS(Inventory),
    FILTER(
        Inventory,
        VAR DaysOwned = DATEDIFF(Inventory[Received_Date], TODAY(), DAY)
        VAR WarrantyPeriod = RELATED(SKU_Master[Warranty_Period_Days])
        RETURN
            DaysOwned >= WarrantyPeriod - 30 &&
            DaysOwned < WarrantyPeriod
    )
)

// Service pending (requested but not scheduled)
Service Pending =
CALCULATE(
    COUNTROWS(Service_Records),
    Service_Records[Service_Status] IN {"Requested", "Open", "Submitted"},
    ISBLANK(Service_Records[Scheduled_Date])
)

// Warranty vs Non-Warranty service breakdown
Warranty Service Requests =
CALCULATE(
    COUNTROWS(Service_Records),
    Service_Records[Warranty_Status] = "Under Warranty"
)

Non-Warranty Service Requests =
CALCULATE(
    COUNTROWS(Service_Records),
    Service_Records[Warranty_Status] <> "Under Warranty"
)

// =============================================================================
// FOLDER: Dashboard Summary KPIs
// =============================================================================

// Warehouse summary for dashboard
Warehouse Summary Units =
"Pending: " & [Pending Arrival] & " | Available: " & [Available Inventory]

// Shipments summary for dashboard
Shipments Summary =
"In Transit: " & [Shipments In Transit] & " | Active: " & [Active Shipments]

// Warranty summary for dashboard
Warranty Summary =
"Active: " & [Active Warranties] & " | Requests: " & [Total Service Requests] & " | Scheduled: " & [Repair Scheduled]

// Service backlog
Service Backlog =
[Service Requested] + [Service Pending]

// Overall operational health score (0-100)
Operational Health Score =
VAR DeliveryScore = MIN([On-Time Delivery %], 100)
VAR ServiceScore = MIN([Service Completion %], 100)
VAR WarrantyScore = DIVIDE([Warranty Service Requests], [Total Service Requests], 0) * 100
RETURN
    (DeliveryScore * 0.4) + (ServiceScore * 0.4) + ((100 - WarrantyScore) * 0.2)

// =============================================================================
// END OF MEASURES
// =============================================================================
